/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
  '/schemas': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Schemas
     * @description List all available schema names.
     */
    get: operations['list_schemas_schemas_get']
    put?: never
    /**
     * Create Schema
     * @description Create a new runtime schema from a JSON definition.
     */
    post: operations['create_schema_schemas_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/schemas/{name}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Schema
     * @description Return the full definition of a schema.
     */
    get: operations['get_schema_schemas__name__get']
    put?: never
    post?: never
    /**
     * Delete Schema
     * @description Delete a runtime schema. Built-in schemas cannot be deleted.
     */
    delete: operations['delete_schema_schemas__name__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/upload': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Upload File
     * @description Upload a spreadsheet and map its headers to the target schema.
     */
    post: operations['upload_file_upload_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sheets': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * List Sheets
     * @description Upload a file and return its sheet names (Excel only).
     */
    post: operations['list_sheets_sheets_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/corrections': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Submit Corrections
     * @description Submit human-verified mapping corrections for a cedent.
     */
    post: operations['submit_corrections_corrections_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sessions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create Session
     * @description Upload a file, get SLM suggestion + preview. Creates a session.
     */
    post: operations['create_session_sessions_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sessions/{session_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Session
     * @description Return current session state.
     */
    get: operations['get_session_sessions__session_id__get']
    put?: never
    post?: never
    /**
     * Delete Session
     * @description Delete a session and clean up its temp file.
     */
    delete: operations['delete_session_sessions__session_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sessions/{session_id}/mappings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Update Session Mappings
     * @description Update the session's mappings with user-edited values.
     */
    put: operations['update_session_mappings_sessions__session_id__mappings_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sessions/{session_id}/target-fields': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Extend Target Fields
     * @description Add custom target fields to a session.
     */
    patch: operations['extend_target_fields_sessions__session_id__target_fields_patch']
    trace?: never
  }
  '/sessions/{session_id}/finalise': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Finalise Session
     * @description Validate rows with the session's current mapping.
     */
    post: operations['finalise_session_sessions__session_id__finalise_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/upload/async': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Upload File Async
     * @description Accept a file for async processing, return job ID immediately.
     */
    post: operations['upload_file_async_upload_async_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/jobs/{job_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Job Status
     * @description Get the status and result of an async job.
     */
    get: operations['get_job_status_jobs__job_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations['health_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export type components = {
  schemas: {
    /**
     * AsyncJobResponse
     * @description POST /upload/async response.
     */
    AsyncJobResponse: {
      /** Job Id */
      job_id: string
    }
    /** Body_create_session_sessions_post */
    Body_create_session_sessions_post: {
      /** File */
      file: string
    }
    /** Body_list_sheets_sheets_post */
    Body_list_sheets_sheets_post: {
      /** File */
      file: string
    }
    /** Body_upload_file_async_upload_async_post */
    Body_upload_file_async_upload_async_post: {
      /** File */
      file: string
    }
    /** Body_upload_file_upload_post */
    Body_upload_file_upload_post: {
      /** File */
      file: string
    }
    /**
     * ColumnMapping
     * @description Maps a source spreadsheet header to a target schema field.
     *
     *     target_field is not validated here — it's validated at the
     *     MappingResult level via validate_against_schema() where the
     *     TargetSchema is known. This allows ColumnMapping to work with
     *     any schema, not just the hardcoded default.
     */
    ColumnMapping: {
      /** Source Header */
      source_header: string
      /** Target Field */
      target_field: string
      /** Confidence */
      confidence: number
    }
    /**
     * ConfidenceReport
     * @description Summarizes mapping quality for human review.
     *
     *     Built from a MappingResult, this report highlights:
     *     - Overall confidence (min and average)
     *     - Which fields have low confidence and need review
     *     - Which target fields were not mapped at all
     */
    ConfidenceReport: {
      /** Min Confidence */
      min_confidence: number
      /** Avg Confidence */
      avg_confidence: number
      /** Low Confidence Fields */
      low_confidence_fields: components['schemas']['ColumnMapping'][]
      /** Missing Fields */
      missing_fields: string[]
    }
    /**
     * CorrectionItem
     * @description A single correction in a POST /corrections request.
     */
    CorrectionItem: {
      /** Source Header */
      source_header: string
      /** Target Field */
      target_field: string
    }
    /**
     * CorrectionRequest
     * @description Request body for POST /corrections.
     */
    CorrectionRequest: {
      /** Cedent Id */
      cedent_id: string
      /** Corrections */
      corrections: components['schemas']['CorrectionItem'][]
    }
    /**
     * CorrectionStoredResponse
     * @description POST /corrections response.
     */
    CorrectionStoredResponse: {
      /** Stored */
      stored: number
    }
    /**
     * DateOrderingRule
     * @description Cross-field rule: one date must not precede another.
     */
    DateOrderingRule: {
      /** Earlier */
      earlier: string
      /** Later */
      later: string
    }
    /**
     * ErrorDetail
     * @description Structured error response body.
     */
    ErrorDetail: {
      /** Error Code */
      error_code: string
      /** Message */
      message: string
      /** Suggestion */
      suggestion: string
    }
    /**
     * ExtendTargetFieldsRequest
     * @description Request body for PATCH /sessions/{session_id}/target-fields.
     */
    ExtendTargetFieldsRequest: {
      /** Fields */
      fields: string[]
    }
    /**
     * FieldDefinition
     * @description Definition of a single target field with type-safe constraints.
     *
     *     Constraints are validated against the field type:
     *     - not_empty: only valid for STRING
     *     - non_negative: only valid for FLOAT
     *     - allowed_values: only valid for CURRENCY
     */
    FieldDefinition: {
      type: components['schemas']['FieldType']
      /**
       * Required
       * @default true
       */
      required: boolean
      /**
       * Not Empty
       * @default false
       */
      not_empty: boolean
      /**
       * Non Negative
       * @default false
       */
      non_negative: boolean
      /** Allowed Values */
      allowed_values?: string[] | null
    }
    /**
     * FieldError
     * @description A validation error for a specific field within a row.
     */
    FieldError: {
      /** Field */
      field: string
      /** Message */
      message: string
      /** Value */
      value?: string | null
    }
    /**
     * FieldType
     * @enum {string}
     */
    FieldType: 'string' | 'date' | 'float' | 'currency'
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * HealthResponse
     * @description GET /health response.
     */
    HealthResponse: {
      /** Status */
      status: string
    }
    /**
     * JobStatusResponse
     * @description GET /jobs/{job_id} response.
     */
    JobStatusResponse: {
      /** Job Id */
      job_id: string
      /** Status */
      status: string
      /** Result */
      result?: {
        [key: string]: unknown
      } | null
      /** Error */
      error?: string | null
    }
    /**
     * MappingResult
     * @description Result of SLM header mapping.
     */
    MappingResult: {
      /** Mappings */
      mappings: components['schemas']['ColumnMapping'][]
      /** Unmapped Headers */
      unmapped_headers: string[]
    }
    /**
     * MappingSession
     * @description Tracks state for an interactive mapping workflow.
     */
    MappingSession: {
      /** Id */
      id: string
      status: components['schemas']['SessionStatus']
      /** Schema Name */
      schema_name: string
      /** File Path */
      file_path: string
      /** Sheet Name */
      sheet_name: string | null
      /** Source Headers */
      source_headers: string[]
      /** Target Fields */
      target_fields: string[]
      /** Mappings */
      mappings: components['schemas']['ColumnMapping'][]
      /** Unmapped Headers */
      unmapped_headers: string[]
      /** Preview Rows */
      preview_rows: {
        [key: string]: unknown
      }[]
      /** Result */
      result?: {
        [key: string]: unknown
      } | null
    }
    /**
     * ProcessingResult
     * @description Full result of processing a spreadsheet: mapping + row validation.
     *
     *     valid_records uses list[dict] because the record model is dynamic —
     *     field names depend on the active TargetSchema. Dicts are the natural
     *     serialization format and avoid complex generic type gymnastics.
     */
    ProcessingResult: {
      mapping: components['schemas']['MappingResult']
      confidence_report: components['schemas']['ConfidenceReport']
      /** Valid Records */
      valid_records: {
        [key: string]: unknown
      }[]
      /** Invalid Records */
      invalid_records: {
        [key: string]: unknown
      }[]
      /** Errors */
      errors: components['schemas']['RowError'][]
    }
    /**
     * RowError
     * @description A validation error for a specific row.
     */
    RowError: {
      /** Row */
      row: number
      /** Error */
      error: string
      /**
       * Field Errors
       * @default []
       */
      field_errors: components['schemas']['FieldError'][]
    }
    /**
     * SLMHint
     * @description Maps common source header aliases to target fields.
     *
     *     Injected into the SLM prompt to improve mapping accuracy.
     *     E.g., "GWP" is a common alias for "Gross_Premium" in reinsurance.
     */
    SLMHint: {
      /** Source Alias */
      source_alias: string
      /** Target */
      target: string
    }
    /**
     * SchemaCreatedResponse
     * @description POST /schemas response.
     */
    SchemaCreatedResponse: {
      /** Name */
      name: string
      /** Fingerprint */
      fingerprint: string
    }
    /**
     * SchemaListResponse
     * @description GET /schemas response.
     */
    SchemaListResponse: {
      /** Schemas */
      schemas: string[]
    }
    /**
     * SessionStatus
     * @enum {string}
     */
    SessionStatus: 'created' | 'finalised'
    /**
     * SheetListResponse
     * @description POST /sheets response.
     */
    SheetListResponse: {
      /** Sheets */
      sheets: string[]
    }
    /**
     * TargetSchema
     * @description A complete target schema definition.
     *
     *     Self-validating: cross-field rules must reference existing DATE fields,
     *     SLM hints must reference existing fields, aliases must be unique.
     */
    TargetSchema: {
      /** Name */
      name: string
      /** Fields */
      fields: {
        [key: string]: components['schemas']['FieldDefinition']
      }
      /**
       * Cross Field Rules
       * @default []
       */
      cross_field_rules: components['schemas']['DateOrderingRule'][]
      /**
       * Slm Hints
       * @default []
       */
      slm_hints: components['schemas']['SLMHint'][]
    }
    /**
     * UpdateMappingsRequest
     * @description Request body for PUT /sessions/{session_id}/mappings.
     */
    UpdateMappingsRequest: {
      /**
       * Mappings
       * @default []
       */
      mappings: components['schemas']['ColumnMapping'][]
      /**
       * Unmapped Headers
       * @default []
       */
      unmapped_headers: string[]
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_schemas_schemas_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SchemaListResponse']
        }
      }
    }
  }
  create_schema_schemas_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          [key: string]: unknown
        }
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SchemaCreatedResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_schema_schemas__name__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        name: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TargetSchema']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_schema_schemas__name__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        name: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  upload_file_upload_post: {
    parameters: {
      query?: {
        /** @description Sheet name for multi-sheet Excel files */
        sheet_name?: string | null
        /** @description Cedent ID for correction cache lookup */
        cedent_id?: string | null
        /** @description Schema name to use (from GET /schemas) */
        schema?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_file_upload_post']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProcessingResult']
        }
      }
      /** @description Invalid data or sheet name */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorDetail']
        }
      }
      /** @description Low confidence or schema validation error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorDetail']
        }
      }
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorDetail']
        }
      }
      /** @description SLM unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorDetail']
        }
      }
    }
  }
  list_sheets_sheets_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_list_sheets_sheets_post']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SheetListResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  submit_corrections_corrections_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CorrectionRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CorrectionStoredResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_session_sessions_post: {
    parameters: {
      query?: {
        /** @description Sheet name for multi-sheet Excel files */
        sheet_name?: string | null
        /** @description Schema name to use (from GET /schemas) */
        schema?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_create_session_sessions_post']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MappingSession']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_session_sessions__session_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MappingSession']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_session_sessions__session_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_session_mappings_sessions__session_id__mappings_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateMappingsRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MappingSession']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  extend_target_fields_sessions__session_id__target_fields_patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ExtendTargetFieldsRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MappingSession']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  finalise_session_sessions__session_id__finalise_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MappingSession']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  upload_file_async_upload_async_post: {
    parameters: {
      query?: {
        /** @description Sheet name for multi-sheet Excel files */
        sheet_name?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_file_async_upload_async_post']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AsyncJobResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_job_status_jobs__job_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JobStatusResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
}
